import { auth, db } from "./firebase-config.js";
import { signInWithEmailAndPassword, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import { collection, doc, setDoc, deleteDoc, onSnapshot, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";
const ADMIN_EMAIL="zaynyt684@gmail.com";const state={forms:[],services:[],links:[],banners:[],broadcast:null};const $=id=>document.getElementById(id);const esc=v=>String(v??"").replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));const slug=t=>String(t||"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,70)||Date.now().toString();const csv=t=>String(t||"").split(",").map(x=>x.trim()).filter(Boolean);function toast(m){const x=document.createElement("div");x.className="toast";x.textContent=m;document.body.appendChild(x);setTimeout(()=>x.remove(),2600)}function show(id){document.querySelectorAll("[data-panel]").forEach(x=>x.classList.add("hidden"));$(id)?.classList.remove("hidden");document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.dataset.tab===id))}window.adminTab=show;
function stats(){if($("statForms"))$("statForms").textContent=state.forms.length;if($("statServices"))$("statServices").textContent=state.services.length;if($("statLinks"))$("statLinks").textContent=state.links.length;if($("statTotal"))$("statTotal").textContent=state.forms.length+state.services.length+state.links.length+state.banners.length+(state.broadcast?.active?1:0);if($("statActive"))$("statActive").textContent=state.banners.filter(x=>x.active).length+(state.broadcast?.active?1:0)}
function forms(){const b=$("formsAdminList");if(!b)return;b.innerHTML=state.forms.length?state.forms.map(f=>`<div class="item"><div><h3>${esc(f.name)}</h3><p>${esc(f.category||"")} · ${esc(f.pdfName||"")}</p></div><div class="actions">${f.pdfName?`<a class="btn light" target="_blank" rel="noopener" href="assets/${encodeURIComponent(f.pdfName)}">Open</a>`:""}<button class="btn danger" data-del-form="${esc(f.id)}">Delete</button></div></div>`).join(""):"<p class='muted'>No forms yet.</p>"}
function services(){const b=$("servicesAdminList");if(!b)return;b.innerHTML=state.services.length?state.services.map(s=>`<div class="item"><div><h3>${esc(s.name)}</h3><p>${esc(s.category||"")} · ${(s.documents||[]).length} documents</p></div><div class="actions"><button class="btn light" data-edit-service="${esc(s.id)}">Edit</button><button class="btn danger" data-del-service="${esc(s.id)}">Delete</button></div></div>`).join(""):"<p class='muted'>No services yet.</p>"}
function links(){const b=$("linksAdminList");if(!b)return;b.innerHTML=state.links.length?state.links.map(l=>`<div class="item"><div><h3>${esc(l.name)}</h3><p>${esc(l.category||"")}</p></div><div class="actions"><a class="btn light" target="_blank" rel="noopener" href="${esc(l.url)}">Open</a><button class="btn danger" data-del-link="${esc(l.id)}">Delete</button></div></div>`).join(""):"<p class='muted'>No links yet.</p>"}
function banners(){const b=$("bannersAdminList");if(!b)return;b.innerHTML=state.banners.length?state.banners.map(x=>`<div class="item"><div><h3>${esc(x.title)}</h3><p>${esc(x.image||"")} · ${x.active?"Active":"Inactive"}</p></div><button class="btn danger" data-del-banner="${esc(x.id)}">Delete</button></div>`).join(""):"<p class='muted'>No posters yet.</p>"}
function broadcastPreview(){const x=$("broadcastPreview");if(x)x.textContent=$("broadcastMessage")?.value.trim()||"Broadcast preview"}function bannerPreview(){const x=$("bannerPreview"),p=$("bannerImage")?.value.trim();if(x)x.innerHTML=p?`<img src="${esc(p)}" alt="Preview" style="max-width:100%;max-height:220px;border-radius:10px" onerror="this.style.display='none'">`:'Poster preview'}
function listen(){onSnapshot(collection(db,"forms"),s=>{state.forms=s.docs.map(d=>({id:d.id,...d.data()}));forms();stats()});onSnapshot(collection(db,"services"),s=>{state.services=s.docs.map(d=>({id:d.id,...d.data()}));services();stats()});onSnapshot(collection(db,"links"),s=>{state.links=s.docs.map(d=>({id:d.id,...d.data()}));links();stats()});onSnapshot(collection(db,"banners"),s=>{state.banners=s.docs.map(d=>({id:d.id,...d.data()}));banners();stats()});onSnapshot(doc(db,"content","broadcast"),s=>{state.broadcast=s.exists()?s.data():null;if(state.broadcast){$("broadcastMessage").value=state.broadcast.message||"";$("broadcastButton").value=state.broadcast.buttonText||"";$("broadcastUrl").value=state.broadcast.url||"";$("broadcastType").value=state.broadcast.type||"info";$("broadcastActive").checked=!!state.broadcast.active;broadcastPreview()}stats()});onSnapshot(doc(db,"settings","site"),s=>{if(!s.exists())return;const x=s.data();const m={settingShopName:"shopname",settingLocation:"location",settingPhone:"phone",settingWhatsapp:"whatsapp",settingAddress:"address",settingHours:"hours"};Object.entries(m).forEach(([id,k])=>{if($(id)&&x[k]!==undefined)$(id).value=x[k]})})}
async function login(){const e=$("adminEmail").value.trim(),p=$("adminPassword").value;$("loginError").textContent="";if(e.toLowerCase()!==ADMIN_EMAIL){$("loginError").textContent="This email is not the authorized admin account.";return}try{await signInWithEmailAndPassword(auth,e,p)}catch(x){$("loginError").textContent=x.code||x.message}}
async function saveForm(){const n=$("formName").value.trim(),pdf=$("formPdfName").value.trim();if(!n||!pdf)return toast("Form name और PDF filename डालें");await setDoc(doc(db,"forms",slug(n)),{name:n,category:$("formCategoryAdmin").value.trim(),keywords:csv($("formKeywords").value),pdfName:pdf,updatedAt:serverTimestamp()},{merge:true});["formName","formCategoryAdmin","formKeywords","formPdfName"].forEach(i=>$(i).value="");toast("Form saved")}
function addDoc(v=""){const r=document.createElement("div");r.className="check-row";r.innerHTML=`<input value="${esc(v)}" placeholder="Required document"><button type="button" class="btn danger">×</button>`;r.querySelector("button").onclick=()=>r.remove();$("docRows").appendChild(r)}function editService(id){const s=state.services.find(x=>x.id===id);if(!s)return;$("serviceName").value=s.name||"";$("serviceEnglish").value=s.englishName||"";$("serviceCategory").value=s.category||"";$("serviceDescription").value=s.description||"";$("serviceKeywords").value=(s.keywords||[]).join(", ");$("serviceNote").value=s.note||"";$("docRows").innerHTML="";(s.documents||[]).forEach(addDoc);show("servicePanel")}
async function saveService(){const n=$("serviceName").value.trim();if(!n)return toast("Service name डालें");const d=[...document.querySelectorAll("#docRows input")].map(x=>x.value.trim()).filter(Boolean);await setDoc(doc(db,"services",slug(n)),{name:n,englishName:$("serviceEnglish").value.trim(),category:$("serviceCategory").value.trim(),description:$("serviceDescription").value.trim(),keywords:csv($("serviceKeywords").value),note:$("serviceNote").value.trim(),documents:d,updatedAt:serverTimestamp()},{merge:true});toast("Service saved")}
async function saveLink(){const n=$("linkName").value.trim(),u=$("linkUrl").value.trim();if(!n||!/^https?:\/\//i.test(u))return toast("Name और valid URL डालें");await setDoc(doc(db,"links",slug(n)),{name:n,category:$("linkCategory").value.trim(),url:u,updatedAt:serverTimestamp()},{merge:true});toast("Link saved")}
async function saveBroadcast(){await setDoc(doc(db,"content","broadcast"),{message:$("broadcastMessage").value.trim(),buttonText:$("broadcastButton").value.trim(),url:$("broadcastUrl").value.trim(),type:$("broadcastType").value,active:$("broadcastActive").checked,updatedAt:serverTimestamp()},{merge:true});toast("Broadcast published")}
async function saveBanner(){const t=$("bannerTitle").value.trim(),im=$("bannerImage").value.trim();if(!t||!im)return toast("Title और image path डालें");await setDoc(doc(db,"banners",slug(t)),{title:t,image:im,description:$("bannerDescription").value.trim(),buttonText:$("bannerButton").value.trim(),url:$("bannerUrl").value.trim(),active:$("bannerActive").checked,updatedAt:serverTimestamp()},{merge:true});["bannerTitle","bannerImage","bannerDescription","bannerButton","bannerUrl"].forEach(i=>$(i).value="");$("bannerActive").checked=true;toast("Poster saved")}
async function saveSettings(){await setDoc(doc(db,"settings","site"),{shopname:$("settingShopName").value.trim(),location:$("settingLocation").value.trim(),phone:$("settingPhone").value.trim(),whatsapp:$("settingWhatsapp").value.trim(),address:$("settingAddress").value.trim(),hours:$("settingHours").value.trim(),updatedAt:serverTimestamp()},{merge:true});toast("Settings saved")}
async function del(c,id){if(!confirm("Delete this item?"))return;await deleteDoc(doc(db,c,id));toast("Deleted")}
function bind(){
$("loginBtn")?.addEventListener("click",login);$("logoutBtn")?.addEventListener("click",()=>signOut(auth));$("adminPassword")?.addEventListener("keydown",e=>{if(e.key==="Enter")login()});$("formSaveBtn")?.addEventListener("click",saveForm);$("serviceSaveBtn")?.addEventListener("click",saveService);$("linkSaveBtn")?.addEventListener("click",saveLink);$("broadcastSaveBtn")?.addEventListener("click",saveBroadcast);$("bannerSaveBtn")?.addEventListener("click",saveBanner);$("settingsSaveBtn")?.addEventListener("click",saveSettings);$("addDocBtn")?.addEventListener("click",()=>addDoc());$("bannerImage")?.addEventListener("input",bannerPreview);$("broadcastMessage")?.addEventListener("input",broadcastPreview);document.addEventListener("click",e=>{const f=e.target.closest("[data-del-form]"),s=e.target.closest("[data-del-service]"),l=e.target.closest("[data-del-link]"),b=e.target.closest("[data-del-banner]"),ed=e.target.closest("[data-edit-service]");if(f)del("forms",f.dataset.delForm);if(s)del("services",s.dataset.delService);if(l)del("links",l.dataset.delLink);if(b)del("banners",b.dataset.delBanner);if(ed)editService(ed.dataset.editService)})}bind();onAuthStateChanged(auth,u=>{if(u?.email?.toLowerCase()===ADMIN_EMAIL){$("loginView").classList.add("hidden");$("dashboardView").classList.remove("hidden");$("adminUser").textContent=u.email;listen()}else{$("loginView").classList.remove("hidden");$("dashboardView").classList.add("hidden")}});