import { auth, db, storage } from "./firebase-config.js";
import { signInWithEmailAndPassword, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import { collection, doc, setDoc, deleteDoc, onSnapshot, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";
import { ref, uploadBytesResumable, getDownloadURL, deleteObject } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-storage.js";

const ADMIN_EMAIL = "zaynyt684@gmail.com";
const state = { forms: [], services: [], links: [] };
const $ = id => document.getElementById(id);
function esc(v){return String(v ?? "").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;");}
function toast(message){const old=document.querySelector(".toast");if(old)old.remove();const el=document.createElement("div");el.className="toast";el.textContent=message;document.body.appendChild(el);setTimeout(()=>el.remove(),3000);}
function slug(text){return String(text||"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,70)||Date.now().toString();}
function csvList(text){return String(text||"").split(",").map(x=>x.trim()).filter(Boolean);}
function show(id){document.querySelectorAll("[data-panel]").forEach(x=>x.classList.add("hidden"));$(id)?.classList.remove("hidden");document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelector(`[data-tab="${id}"]`)?.classList.add("active");}
window.adminTab=show;
function updateStats(){$("statForms").textContent=state.forms.length;$ ("statServices").textContent=state.services.length;$ ("statLinks").textContent=state.links.length;$ ("statTotal").textContent=state.forms.length+state.services.length+state.links.length;}
function renderForms(){const box=$("formsAdminList");if(!box)return;box.innerHTML=state.forms.length?state.forms.map((f,i)=>`<div class="item rise" style="animation-delay:${Math.min(i,10)*35}ms"><div><h3>${esc(f.name)}</h3><p>${esc(f.category||"")}</p><span class="status">PDF ready</span></div><div class="admin-actions"><a class="btn btn-light" target="_blank" rel="noopener" href="${esc(f.fileUrl)}">Open</a><button class="btn btn-danger" data-delete-form="${esc(f.id)}">Delete</button></div></div>`).join(""):"<div class='empty'>अभी कोई Firebase form नहीं है।</div>";}
function renderServices(){const box=$("servicesAdminList");if(!box)return;box.innerHTML=state.services.length?state.services.map((s,i)=>`<div class="item rise" style="animation-delay:${Math.min(i,10)*35}ms"><div><h3>${esc(s.name)}</h3><p>${esc(s.category||"")} · ${esc(s.documents?.length||0)} documents</p></div><div class="admin-actions"><button class="btn btn-light" data-edit-service="${esc(s.id)}">Edit</button><button class="btn btn-danger" data-delete-service="${esc(s.id)}">Delete</button></div></div>`).join(""):"<div class='empty'>अभी कोई Firebase service नहीं है।</div>";}
function renderLinks(){const box=$("linksAdminList");if(!box)return;box.innerHTML=state.links.length?state.links.map((l,i)=>`<div class="item rise" style="animation-delay:${Math.min(i,10)*35}ms"><div><h3>${esc(l.name)}</h3><p>${esc(l.category||"")}</p></div><div class="admin-actions"><a class="btn btn-light" target="_blank" rel="noopener" href="${esc(l.url)}">Open</a><button class="btn btn-danger" data-delete-link="${esc(l.id)}">Delete</button></div></div>`).join(""):"<div class='empty'>अभी कोई online link नहीं है।</div>";}
function listenData(){onSnapshot(collection(db,"forms"),snap=>{state.forms=snap.docs.map(d=>({id:d.id,...d.data()}));renderForms();updateStats();});onSnapshot(collection(db,"services"),snap=>{state.services=snap.docs.map(d=>({id:d.id,...d.data()}));renderServices();updateStats();});onSnapshot(collection(db,"links"),snap=>{state.links=snap.docs.map(d=>({id:d.id,...d.data()}));renderLinks();updateStats();});}
async function login(){const email=$("adminEmail").value.trim();const password=$("adminPassword").value;$("loginError").textContent="";if(email.toLowerCase()!==ADMIN_EMAIL.toLowerCase()){$("loginError").textContent="यह admin account नहीं है।";return;}try{await signInWithEmailAndPassword(auth,email,password);}catch(e){$("loginError").textContent="Login failed: "+(e.code||e.message);}}
async function uploadPdf(file,formId){if(!file)return null;const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_");const storageRef=ref(storage,`forms/${formId}/${Date.now()}-${safe}`);const task=uploadBytesResumable(storageRef,file,{contentType:file.type||"application/pdf"});return new Promise((resolve,reject)=>{task.on("state_changed",snap=>{$("uploadBar").style.width=((snap.bytesTransferred/snap.totalBytes)*100)+"%";},reject,async()=>resolve(await getDownloadURL(task.snapshot.ref)));});}
async function saveForm(){const name=$("formName").value.trim();const category=$("formCategoryAdmin").value.trim()||"General";const file=$("formPdf").files[0];if(!name){toast("Form name डालें");return;}const id=slug(name);let fileUrl="";if(file){if(file.type!=="application/pdf"){toast("सिर्फ PDF upload करें");return;}if(file.size>20*1024*1024){toast("PDF 20 MB से छोटी रखें");return;}$("uploadBar").style.width="0";fileUrl=await uploadPdf(file,id);}const existing=state.forms.find(x=>x.id===id);await setDoc(doc(db,"forms",id),{name,category,fileUrl:fileUrl||existing?.fileUrl||"",keywords:csvList($("formKeywords").value),updatedAt:serverTimestamp()},{merge:true});$("formName").value="";$("formCategoryAdmin").value="";$("formKeywords").value="";$("formPdf").value="";toast("Form saved");}
async function saveService(){const name=$("serviceName").value.trim();if(!name){toast("Service name डालें");return;}const id=slug(name);const docs=[...document.querySelectorAll("#docRows input")].map(x=>x.value.trim()).filter(Boolean);await setDoc(doc(db,"services",id),{name,englishName:$("serviceEnglish").value.trim(),category:$("serviceCategory").value.trim()||"General",description:$("serviceDescription").value.trim(),documents:docs,keywords:csvList($("serviceKeywords").value),note:$("serviceNote").value.trim(),updatedAt:serverTimestamp()},{merge:true});clearServiceEditor();toast("Service saved");}
function clearServiceEditor(){["serviceName","serviceEnglish","serviceCategory","serviceDescription","serviceKeywords","serviceNote"].forEach(id=>$(id).value="");$("docRows").innerHTML="";}
function addDocRow(value=""){const row=document.createElement("div");row.className="check-row";row.innerHTML=`<input value="${esc(value)}" placeholder="Required document"><button type="button" class="btn btn-danger">×</button>`;row.querySelector("button").onclick=()=>row.remove();$("docRows").appendChild(row);}
function editService(id){const s=state.services.find(x=>x.id===id);if(!s)return;$("serviceName").value=s.name||"";$("serviceEnglish").value=s.englishName||"";$("serviceCategory").value=s.category||"";$("serviceDescription").value=s.description||"";$("serviceKeywords").value=(s.keywords||[]).join(", ");$("serviceNote").value=s.note||"";$("docRows").innerHTML="";(s.documents||[]).forEach(addDocRow);show("servicePanel");window.scrollTo({top:0,behavior:"smooth"});}
async function saveLink(){const name=$("linkName").value.trim(),url=$("linkUrl").value.trim(),category=$("linkCategory").value.trim()||"Official";if(!name||!/^https?:\/\//i.test(url)){toast("Name और valid URL डालें");return;}const id=slug(name);await setDoc(doc(db,"links",id),{name,url,category,updatedAt:serverTimestamp()},{merge:true});$("linkName").value="";$("linkUrl").value="";$("linkCategory").value="";toast("Link saved");}
async function removeForm(id){const f=state.forms.find(x=>x.id===id);if(!f||!confirm("इस form को delete करें?"))return;await deleteDoc(doc(db,"forms",id));if(f.storagePath){try{await deleteObject(ref(storage,f.storagePath));}catch{}}toast("Form deleted");}
async function removeService(id){if(!confirm("इस service को delete करें?"))return;await deleteDoc(doc(db,"services",id));toast("Service deleted");}
async function removeLink(id){if(!confirm("इस link को delete करें?"))return;await deleteDoc(doc(db,"links",id));toast("Link deleted");}
function bind(){$("loginBtn").onclick=login;$ ("logoutBtn").onclick=()=>signOut(auth);$("formSaveBtn").onclick=saveForm;$("serviceSaveBtn").onclick=saveService;$("linkSaveBtn").onclick=saveLink;$("addDocBtn").onclick=()=>addDocRow();$("adminPassword").addEventListener("keydown",e=>{if(e.key==="Enter")login();});document.addEventListener("click",e=>{const f=e.target.closest("[data-delete-form]"),s=e.target.closest("[data-delete-service]"),l=e.target.closest("[data-delete-link]"),ed=e.target.closest("[data-edit-service]");if(f)removeForm(f.dataset.deleteForm);if(s)removeService(s.dataset.deleteService);if(l)removeLink(l.dataset.deleteLink);if(ed)editService(ed.dataset.editService);});}
bind();
onAuthStateChanged(auth,user=>{if(user){if(user.email?.toLowerCase()!==ADMIN_EMAIL.toLowerCase()){signOut(auth);return;}$("loginView").classList.add("hidden");$("dashboardView").classList.remove("hidden");$("adminUser").textContent=user.email||"Admin";listenData();}else{$("loginView").classList.remove("hidden");$("dashboardView").classList.add("hidden");}});
