import { auth, db } from "./firebase-config.js";
import { signInWithEmailAndPassword, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import { collection, doc, setDoc, deleteDoc, onSnapshot, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";

const ADMIN_EMAIL = "zaynyt684@gmail.com";
const state = { forms: [], services: [], links: [] };
const $ = id => document.getElementById(id);
const esc = v => String(v ?? "").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;");
const slug = t => String(t||"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,70) || Date.now().toString();
const csvList = t => String(t||"").split(",").map(x=>x.trim()).filter(Boolean);
function toast(message){const old=document.querySelector(".toast");if(old)old.remove();const e=document.createElement("div");e.className="toast";e.textContent=message;document.body.appendChild(e);setTimeout(()=>e.remove(),2500);}
function show(id){document.querySelectorAll("[data-panel]").forEach(x=>x.classList.add("hidden"));$(id)?.classList.remove("hidden");document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelector(`[data-tab="${id}"]`)?.classList.add("active");}
window.adminTab=show;
function updateStats(){$("statForms").textContent=state.forms.length;$("statServices").textContent=state.services.length;$("statLinks").textContent=state.links.length;$("statTotal").textContent=state.forms.length+state.services.length+state.links.length;}
function renderForms(){const b=$("formsAdminList");if(!b)return;b.innerHTML=state.forms.length?state.forms.map(f=>`<div class="item rise"><div><h3>${esc(f.name)}</h3><p>${esc(f.category||"")}</p><span class="status">${f.fileUrl?"PDF linked":"No PDF"}</span></div><div class="admin-actions">${f.fileUrl?`<a class="btn btn-light" target="_blank" rel="noopener" href="${esc(f.fileUrl)}">Open</a>`:""}<button class="btn btn-danger" data-delete-form="${esc(f.id)}">Delete</button></div></div>`).join(""):"<div class='empty'>अभी कोई Firebase form नहीं है।</div>";}
function renderServices(){const b=$("servicesAdminList");if(!b)return;b.innerHTML=state.services.length?state.services.map(s=>`<div class="item rise"><div><h3>${esc(s.name)}</h3><p>${esc(s.category||"")} · ${(s.documents||[]).length} documents</p></div><div class="admin-actions"><button class="btn btn-light" data-edit-service="${esc(s.id)}">Edit</button><button class="btn btn-danger" data-delete-service="${esc(s.id)}">Delete</button></div></div>`).join(""):"<div class='empty'>अभी कोई Firebase service नहीं है।</div>";}
function renderLinks(){const b=$("linksAdminList");if(!b)return;b.innerHTML=state.links.length?state.links.map(l=>`<div class="item rise"><div><h3>${esc(l.name)}</h3><p>${esc(l.category||"")}</p></div><div class="admin-actions"><a class="btn btn-light" target="_blank" rel="noopener" href="${esc(l.url)}">Open</a><button class="btn btn-danger" data-delete-link="${esc(l.id)}">Delete</button></div></div>`).join(""):"<div class='empty'>अभी कोई online link नहीं है।</div>";}
function listenData(){onSnapshot(collection(db,"forms"),s=>{state.forms=s.docs.map(d=>({id:d.id,...d.data()}));renderForms();updateStats();});onSnapshot(collection(db,"services"),s=>{state.services=s.docs.map(d=>({id:d.id,...d.data()}));renderServices();updateStats();});onSnapshot(collection(db,"links"),s=>{state.links=s.docs.map(d=>({id:d.id,...d.data()}));renderLinks();updateStats();});}
async function login(){const email=$("adminEmail").value.trim(),password=$("adminPassword").value;$("loginError").textContent="";if(email.toLowerCase()!==ADMIN_EMAIL.toLowerCase()){$("loginError").textContent="यह admin account नहीं है।";return;}try{await signInWithEmailAndPassword(auth,email,password);}catch(e){$("loginError").textContent="Login failed: "+(e.code||e.message);}}
async function saveForm(){const name=$("formName").value.trim(),category=$("formCategoryAdmin").value.trim()||"General",file=$("formPdf").files[0];if(!name){toast("Form name डालें");return;}if(file&&file.type!=="application/pdf"){toast("सिर्फ PDF चुनें");return;}const id=slug(name);const fileUrl=file?"assets/"+file.name:"";const existing=state.forms.find(x=>x.id===id);await setDoc(doc(db,"forms",id),{name,category,fileUrl:fileUrl||existing?.fileUrl||"",keywords:csvList($("formKeywords").value),updatedAt:serverTimestamp()},{merge:true});toast(file?"Form data saved. PDF को GitHub assets folder में upload करें।":"Form saved");$("formName").value="";$("formCategoryAdmin").value="";$("formKeywords").value="";$("formPdf").value="";}
function addDocRow(value=""){const r=document.createElement("div");r.className="check-row";r.innerHTML=`<input value="${esc(value)}" placeholder="Required document"><button type="button" class="btn btn-danger">×</button>`;r.querySelector("button").onclick=()=>r.remove();$("docRows").appendChild(r);}
function clearServiceEditor(){["serviceName","serviceEnglish","serviceCategory","serviceDescription","serviceKeywords","serviceNote"].forEach(id=>$(id).value="");$("docRows").innerHTML="";}
function editService(id){const s=state.services.find(x=>x.id===id);if(!s)return;$("serviceName").value=s.name||"";$("serviceEnglish").value=s.englishName||"";$("serviceCategory").value=s.category||"";$("serviceDescription").value=s.description||"";$("serviceKeywords").value=(s.keywords||[]).join(", ");$("serviceNote").value=s.note||"";$("docRows").innerHTML="";(s.documents||[]).forEach(addDocRow);show("servicePanel");window.scrollTo({top:0,behavior:"smooth"});}
async function saveService(){const name=$("serviceName").value.trim();if(!name){toast("Service name डालें");return;}const id=slug(name),docs=[...document.querySelectorAll("#docRows input")].map(x=>x.value.trim()).filter(Boolean);await setDoc(doc(db,"services",id),{name,englishName:$("serviceEnglish").value.trim(),category:$("serviceCategory").value.trim()||"General",description:$("serviceDescription").value.trim(),documents:docs,keywords:csvList($("serviceKeywords").value),note:$("serviceNote").value.trim(),updatedAt:serverTimestamp()},{merge:true});clearServiceEditor();toast("Service saved");}
async function saveLink(){const name=$("linkName").value.trim(),url=$("linkUrl").value.trim(),category=$("linkCategory").value.trim()||"Official";if(!name||!/^https?:\/\//i.test(url)){toast("Name और valid URL डालें");return;}await setDoc(doc(db,"links",slug(name)),{name,url,category,updatedAt:serverTimestamp()},{merge:true});$("linkName").value="";$("linkUrl").value="";$("linkCategory").value="";toast("Link saved");}
async function removeForm(id){if(!confirm("इस form को delete करें?"))return;await deleteDoc(doc(db,"forms",id));toast("Form deleted");}
async function removeService(id){if(!confirm("इस service को delete करें?"))return;await deleteDoc(doc(db,"services",id));toast("Service deleted");}
async function removeLink(id){if(!confirm("इस link को delete करें?"))return;await deleteDoc(doc(db,"links",id));toast("Link deleted");}
function bind(){if($("loginBtn"))$("loginBtn").onclick=login;if($("logoutBtn"))$("logoutBtn").onclick=()=>signOut(auth);if($("formSaveBtn"))$("formSaveBtn").onclick=saveForm;if($("serviceSaveBtn"))$("serviceSaveBtn").onclick=saveService;if($("linkSaveBtn"))$("linkSaveBtn").onclick=saveLink;if($("addDocBtn"))$("addDocBtn").onclick=()=>addDocRow();if($("adminPassword"))$("adminPassword").addEventListener("keydown",e=>{if(e.key==="Enter")login();});document.addEventListener("click",e=>{const f=e.target.closest("[data-delete-form]"),s=e.target.closest("[data-delete-service]"),l=e.target.closest("[data-delete-link]"),ed=e.target.closest("[data-edit-service]");if(f)removeForm(f.dataset.deleteForm);if(s)removeService(s.dataset.deleteService);if(l)removeLink(l.dataset.deleteLink);if(ed)editService(ed.dataset.editService);});}
bind();
onAuthStateChanged(auth,user=>{if(user){if(user.email?.toLowerCase()!==ADMIN_EMAIL.toLowerCase()){signOut(auth);return;}$("loginView").classList.add("hidden");$("dashboardView").classList.remove("hidden");$("adminUser").textContent=user.email||"Admin";listenData();}else{$("loginView").classList.remove("hidden");$("dashboardView").classList.add("hidden");}});
